"""provider daily quota usage

Revision ID: 430fd028114c
Revises: 7ea3e37e1e87
Create Date: 2026-08-04 17:53:42.073915
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import aidss.db.base
revision: str = '430fd028114c'
down_revision: str | None = '7ea3e37e1e87'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_quota_usage',
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('updated_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'usage_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_quota_usage')
    # ### end Alembic commands ###
