"""initial schema (phases 1-3)

Revision ID: 60b76ad1dd80
Revises: 
Create Date: 2026-08-04 12:00:41.083710
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import aidss.db.base
revision: str = '60b76ad1dd80'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('adapter_name', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('default_model', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('input_cost_per_1k', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('output_cost_per_1k', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assets',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', name='uq_asset_ticker_exchange')
    )
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'AI', 'SYSTEM', name='actortype', native_enum=False, length=10), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity_created', 'audit_logs', ['entity', 'created_at'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('storage_uri', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_prompt_name_version')
    )
    op.create_table('scheduler_jobs',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('cron_expr', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('next_run_at', aidss.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_jobs_next_run_at'), 'scheduler_jobs', ['next_run_at'], unique=False)
    op.create_table('system_configuration',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_config_scope_key')
    )
    op.create_table('users',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('VIEWER', 'INVESTOR', 'ADMIN', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('user_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('context_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('analysis_type', sa.String(length=40), nullable=False),
    sa.Column('generated_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('context_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_asset_generated', 'analysis_results', ['asset_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_asset_id'), 'analysis_results', ['asset_id'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timeframe', 'timestamp', name='uq_feature_identity')
    )
    op.create_table('fundamental_metrics',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('ingested_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period', 'period_type', 'metric_name', name='uq_fundamental_identity')
    )
    op.create_table('historical_prices',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('ingested_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timeframe', 'timestamp', name='uq_price_asset_timeframe_ts')
    )
    op.create_index('ix_price_asset_tf_ts', 'historical_prices', ['asset_id', 'timeframe', 'timestamp'], unique=False)
    op.create_table('job_queue',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('scheduler_job_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheduler_job_id'], ['scheduler_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_queue_status'), 'job_queue', ['status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('knowledge_base_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', aidss.db.base.Embedding(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_base.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'chunk_index', name='uq_knowledge_chunk_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_knowledge_base_id'), 'knowledge_chunks', ['knowledge_base_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('user_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('user_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_portfolio_user_name')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('provider_ingestion_runs',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=80), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('range_start', aidss.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('range_end', aidss.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', aidss.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_indicators',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('indicator_name', sa.String(length=60), nullable=False),
    sa.Column('params_key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timeframe', 'timestamp', 'indicator_name', 'params_key', name='uq_indicator_identity')
    )
    op.create_index('ix_indicator_lookup', 'technical_indicators', ['asset_id', 'timeframe', 'indicator_name', 'timestamp'], unique=False)
    op.create_table('ticker_news_schedules',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('user_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('cron_expression', sa.String(length=120), nullable=False),
    sa.Column('preset_label', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NEEDS_ATTENTION', name='schedulestatus', native_enum=False, length=20), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', aidss.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', aidss.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', 'cron_expression', name='uq_schedule_user_asset_cron')
    )
    op.create_index(op.f('ix_ticker_news_schedules_next_run_at'), 'ticker_news_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_ticker_news_schedules_user_id'), 'ticker_news_schedules', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('user_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_watchlist_user_name')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('conversation_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=60), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('prompt_template_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_message_created', 'ai_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('news_items',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('schedule_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('body_summary', sa.Text(), nullable=True),
    sa.Column('published_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['ticker_news_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_asset_published', 'news_items', ['asset_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_news_items_asset_id'), 'news_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_news_items_dedup_hash'), 'news_items', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_table('portfolio_analysis',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('portfolio_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('diversification_score', sa.Float(), nullable=True),
    sa.Column('sector_concentration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_matrix', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('simulated_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_analysis_portfolio_id'), 'portfolio_analysis', ['portfolio_id'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('portfolio_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('input_method', sa.Enum('MANUAL', 'IMPORT', name='holdinginputmethod', native_enum=False, length=20), nullable=False),
    sa.Column('updated_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'asset_id', name='uq_holding_portfolio_asset')
    )
    op.create_index(op.f('ix_portfolio_holdings_portfolio_id'), 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('analysis_result_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('label', sa.Enum('STRONG_BUY', 'BUY', 'WATCHLIST', 'HOLD', 'REDUCE', 'SELL', name='recommendationlabel', native_enum=False, length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('supporting_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conflicting_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('bullish_scenario', sa.Text(), nullable=False),
    sa.Column('bearish_scenario', sa.Text(), nullable=False),
    sa.Column('support_level', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('resistance_level', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('target_price_method', sa.String(length=200), nullable=True),
    sa.Column('suggested_stop', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('horizon', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='investmenthorizon', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='ck_confidence_range'),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_analysis_result_id'), 'recommendations', ['analysis_result_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('analysis_result_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('portfolio_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('risk_type', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(analysis_result_id IS NOT NULL) OR (portfolio_id IS NOT NULL)', name='ck_risk_scope_present'),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('watchlist_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'asset_id', name='uq_watchlist_item_asset')
    )
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('investment_journal',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('user_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=True),
    sa.Column('decision', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recommendation_ref', aidss.db.base.GUID(), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_ref'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_journal_user_id'), 'investment_journal', ['user_id'], unique=False)
    op.create_table('news_embeddings',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('news_item_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', aidss.db.base.Embedding(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_item_id', 'chunk_index', name='uq_news_embedding_chunk')
    )
    op.create_index(op.f('ix_news_embeddings_news_item_id'), 'news_embeddings', ['news_item_id'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('news_item_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_news_item_id'), 'sentiment_scores', ['news_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_scores_news_item_id'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_news_embeddings_news_item_id'), table_name='news_embeddings')
    op.drop_table('news_embeddings')
    op.drop_index(op.f('ix_investment_journal_user_id'), table_name='investment_journal')
    op.drop_table('investment_journal')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_recommendations_analysis_result_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_portfolio_holdings_portfolio_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_analysis_portfolio_id'), table_name='portfolio_analysis')
    op.drop_table('portfolio_analysis')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_dedup_hash'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_asset_id'), table_name='news_items')
    op.drop_index('ix_news_asset_published', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_index('ix_ai_message_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_ticker_news_schedules_user_id'), table_name='ticker_news_schedules')
    op.drop_index(op.f('ix_ticker_news_schedules_next_run_at'), table_name='ticker_news_schedules')
    op.drop_table('ticker_news_schedules')
    op.drop_index('ix_indicator_lookup', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_table('provider_ingestion_runs')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_base_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_job_queue_status'), table_name='job_queue')
    op.drop_table('job_queue')
    op.drop_index('ix_price_asset_tf_ts', table_name='historical_prices')
    op.drop_table('historical_prices')
    op.drop_table('fundamental_metrics')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_analysis_results_asset_id'), table_name='analysis_results')
    op.drop_index('ix_analysis_asset_generated', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_scheduler_jobs_next_run_at'), table_name='scheduler_jobs')
    op.drop_table('scheduler_jobs')
    op.drop_table('prompt_templates')
    op.drop_table('knowledge_base')
    op.drop_index('ix_audit_entity_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
