"""scheduler leader lease

Revision ID: 7ea3e37e1e87
Revises: 371022dfaa5b
Create Date: 2026-08-04 16:36:50.699451
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import aidss.db.base
revision: str = '7ea3e37e1e87'
down_revision: str | None = '371022dfaa5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_leases',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('holder', sa.String(length=120), nullable=False),
    sa.Column('acquired_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_leader_leases_expires_at'), 'leader_leases', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leader_leases_expires_at'), table_name='leader_leases')
    op.drop_table('leader_leases')
    # ### end Alembic commands ###
