"""store recommendation translations alongside the original

Revision ID: df94aedf2f33
Revises: fb6d29bee29c
Create Date: 2026-08-05 12:15:07.618947
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'df94aedf2f33'
down_revision: str | None = 'fb6d29bee29c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `server_default` on both, which autogenerate does not add: a NOT NULL
    # column without one fails outright on a table that already has rows, and
    # this one does. Existing recommendations are the original text in the
    # default output language with no rendering yet, which is exactly what
    # these defaults say.
    op.add_column(
        'recommendations',
        sa.Column(
            'language', sa.String(length=5), nullable=False, server_default='id'
        ),
    )
    op.add_column(
        'recommendations',
        sa.Column(
            'translations',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=False,
            server_default='{}',
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'translations')
    op.drop_column('recommendations', 'language')
    # ### end Alembic commands ###
