"""monitoring: quote snapshots and alerts

Revision ID: fb6d29bee29c
Revises: 430fd028114c
Create Date: 2026-08-05 09:17:36.202655
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import aidss.db.base
revision: str = 'fb6d29bee29c'
down_revision: str | None = '430fd028114c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('user_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('kind', sa.Enum('level_approached', 'level_crossed', 'stance_changed', 'limit_proximity', 'suggested_stop_reached', 'unusual_move', name='alertkind', native_enum=False, length=30), nullable=False),
    sa.Column('direction', sa.Enum('up', 'down', 'none', name='alertdirection', native_enum=False, length=10), nullable=False),
    sa.Column('observed_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('triggered_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', aidss.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key'),
    sa.UniqueConstraint('dedup_key', name='uq_alert_dedup')
    )
    op.create_index('ix_alert_user_triggered', 'alerts', ['user_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('quote_snapshots',
    sa.Column('id', aidss.db.base.GUID(), nullable=False),
    sa.Column('asset_id', aidss.db.base.GUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('quoted_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('observed_at', aidss.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_asset_observed', 'quote_snapshots', ['asset_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_quote_snapshots_asset_id'), 'quote_snapshots', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_snapshots_asset_id'), table_name='quote_snapshots')
    op.drop_index('ix_quote_asset_observed', table_name='quote_snapshots')
    op.drop_table('quote_snapshots')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_index('ix_alert_user_triggered', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
